/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ueo4TYwPgjP
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import {
  PopoverTrigger,
  PopoverContent,
  Popover,
} from "@/components/ui/popover"
import Image from "next/image"

export function NavMenu() {
  return (
    <nav className="sticky top-0 z-10 backdrop-blur-md shadow">
      <div className="flex items-center justify-between h-14 px-4 border-b md:px-6 bg-opacity-70 backdrop-filter backdrop-blur-lg">
        <Link className="font-semibold" href="/">
          Traders of Space
        </Link>
        <div className="flex items-center gap-4">
          <Popover>
            <PopoverTrigger asChild>
              <Button
                className="rounded-full w-8 h-8 border-2 border-gray-100"
                size="icon"
                variant="ghost"
              >
                <Image
                  alt="Avatar"
                  className="rounded-full"
                  height="32"
                  src="/astronaut.jpeg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </PopoverTrigger>
            <PopoverContent className="mt-1 w-48">
              <div>
                <Link
                  className="group flex items-center w-full px-3 py-1 text-sm rounded-md bg-gray-100/50 translate-y-0.5  dark:bg-gray-800/50"
                  href="/profile"
                >
                  Profile
                </Link>
              </div>
              <div>
                <Link
                  className="group flex items-center w-full px-3 py-1 text-sm rounded-md bg-white hover:bg-gray-100 hover:text-gray-900 dark:hover:bg-gray-800 dark:hover:text-gray-50"
                  href="#"
                >
                  Sign out
                </Link>
              </div>
            </PopoverContent>
          </Popover>
        </div>
      </div>
    </nav>
  )
}
